# Generated by Django 4.2.7 on 2023-11-29 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='categ',
            name='name',
            field=models.CharField(default=1, max_length=250, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='categ',
            name='slug',
            field=models.SlugField(default='1', max_length=250, unique=True),
            preserve_default=False,
        ),
    ]
