# Generated by Django 4.2.7 on 2023-12-17 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_cart_items'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart_items',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
